### ISSUE TITLE
[Feature Request] Export/Print the full graph

### ISSUE THREAD

**Issue by TomCarton** [git-up/GitUp#856] opened 2022-08-08 15:34 UTC
Allow users to generate an image of the complete graph. In order to get the big picture without having to scroll from page to page.
Would even be nice to be allowed to export the result as a pdf or print it.

**Comment by lucasderraugh** [comment] 2022-08-08 16:15
Duplicate of #701

**Closed** 2022-08-08 16:15 UTC
