### ISSUE TITLE
[Feature request] More space at the top of map view.

### ISSUE THREAD

**Issue by NikKovIos** [git-up/GitUp#890] opened 2022-12-16 18:25 UTC
I'd like to have more space at the top, because when branch names are long they not fully visible.

![image](https://user-images.githubusercontent.com/16647690/208164485-0e79d8a7-b1d3-4e87-ac65-71533489b561.png)

**Comment by lucasderraugh** [comment] 2022-12-16 18:39
Duplicate of #94.

**Closed by lucasderraugh** 2022-12-16 18:39 UTC
