### ISSUE TITLE
Feature request: “universal” binary for better performance on Apple Silicon Macs

### ISSUE THREAD

**Issue by aviflax** [git-up/GitUp#712] opened 2020-11-24 17:07 UTC
I guess I could build the project myself, but I’m not proficient with Xcode and then I wouldn’t get updates. So I’d prefer to use an official build if possible.

Thank you!

**Comment by lucasderraugh** [comment] 2020-11-24 18:05
This is a dupe of #693. I openssl doesn't have a distribution that includes the correct configuration yet but perhaps I'll just make a fork that has the configuration.

**Closed by lucasderraugh** 2020-11-24 18:05 UTC

**Comment by aviflax** [comment] 2020-11-24 22:06
Ah, yes, that it is!

I'd searched for "ARM" and "M1" and "Apple Silicon" but not for "universal" 🤦

Thanks!
