### ISSUE TITLE
Linux version please

### ISSUE THREAD

**Issue by COLABORATI** [git-up/GitUp#348] opened 2017-08-04 10:19 UTC
Please release this software for Linux. Thank you.

**Comment by hawkrives** [comment] 2017-08-04 11:46
Duplicate of https://github.com/git-up/GitUp/issues/160

**Comment by wmertens** [comment] 2017-08-07 11:18
@COLABORATI it is very difficult to port this project to Linux. You will have to create a new UI in some framework, and bridge to GitUpKit (which is written in ObjectiveC). I am certain @swisspol won't be doing that, but you are welcome to start a project that does this…

**Comment by swisspol** [comment] 2017-08-07 13:29
Duo of #160

**Closed by swisspol** 2017-08-07 13:29 UTC
Labels: question
