### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by pys1992** [git-up/GitUp#819] opened 2022-05-07 05:59 UTC
os: macos Monterey 12.3.1
gitup: Version 1.3.1 (1044)

Menu covered by the name.

<img width="916" alt="image" src="https://user-images.githubusercontent.com/44765369/167240767-35c43281-679e-40df-b12c-91ecf412e03d.png">

**Comment by lucasderraugh** [comment] 2022-05-07 21:57
Dupe of #790. Thank you though.

**Closed** 2022-05-07 21:57 UTC
