### ISSUE TITLE
"Failed writing snapshots" message when opening repo on macOS 10.13 with APFS

### ISSUE THREAD

**Issue by mark-anders** [git-up/GitUp#322] opened 2017-06-09 23:00 UTC
I'm seeing this since upgrading to 10.13.  It happens on every repo I open.

**Comment by salutis** [comment] 2017-06-11 21:23
Duplicate of #144.

**Comment by aleksandergrzyb** [comment] 2017-09-26 06:02
I'm having this issue too.

**Comment by wmertens** [comment] 2017-09-27 09:41
Confirm fixed in 1.0.9

**Comment by salutis** [comment] 2017-09-27 15:19
@swisspol This one can be closed.

**Closed** 2017-09-27 15:41 UTC
Labels: bug
