### ISSUE TITLE
Catch-all keep rule in .gitignore works with git but not shown in GitUp

### ISSUE THREAD

**Issue by ppo** [git-up/GitUp#668] opened 2020-04-10 02:59 UTC
It seems there's a problem with "keep" rules in the `.gitignore`.

With the following files and rules:
```
# Files                # .gitignore
.env                   *.env
.env.local             *.env.*
.env.example           !*.example
.env.local.example
```

`git status` shows the example files under the untracked files but they don't appear in the "Working Directory" pane in GitUp.
```
Untracked files:
	.env.example
	.env.local.example
```

With the rule `!.env.*.example`, GitUp shows well the `.env.local.example` file.

**Comment by tewe** [comment] 2021-06-28 12:42
Duplicate of #148

**Closed** 2021-06-29 07:46 UTC
