### ISSUE TITLE
Fix certain branches vertically in the UI

### ISSUE THREAD

**Issue by szpasztor** [git-up/GitUp#346] opened 2017-07-19 10:51 UTC
Hi,
Our team is following the gitflow branching model. However, with multiple developers, it sometimes becomes very hard to visually discern branches, what happened where, etc.  I'm wondering if there's a way to "fix" certain branches vertically, so their commits are always in one vertical line.
Essentially, the history would look like this (taken from http://nvie.com/posts/a-successful-git-branching-model/): 
![image](https://user-images.githubusercontent.com/8398290/28363451-ece10948-6c80-11e7-92a7-f6f9df63d7c4.png)

This way, the long running master, develop branches would be way easier to manage, especially in big teams.

Best Regards,
Szabolcs

**Comment by deyton** [comment] 2017-08-12 19:41
This sounds like a duplicate of https://github.com/git-up/GitUp/issues/342.

**Comment by sesam** [comment] 2022-03-09 01:30
Suggest closing this due to:
1. The graph in this issue shows time with newest at the bottom, which is the opposite of what gitup does.
2. #342 is explaining some more specific use cases and is also more implementable.

**Comment by lucasderraugh** [comment] 2022-03-09 01:59
I agree, #342 branch pinning would be more generalizable I think.

**Closed by lucasderraugh** 2022-03-09 01:59 UTC
Labels: enhancement
