### ISSUE TITLE
Feature Request: Add 'Commit + Push' button to commit view

### ISSUE THREAD

**Issue by SteveEdson** [git-up/GitUp#880] opened 2022-12-12 23:00 UTC
This is extremely lazy of me, but I love Gitup and spend 99% of my time in the commit view. I just wish there was a quicker way to push that commit once I was finished, rather than switching to the map view.

- A `Commit + Push` / `Push` button on the commit view screen would be amazing
- At least let the `Cmd` + `Shift` + `P` shortcut work on the commit view tab, it only works on map view right now.

Thanks

**Comment by lucasderraugh** [comment] 2022-12-16 14:58
Going to close this out as a duplicate of https://github.com/git-up/GitUp/issues/506

**Closed by lucasderraugh** 2022-12-16 14:58 UTC
Labels: enhancement

**Comment by SteveEdson** [comment] 2022-12-16 15:53
That's fine, can a note be added on the other issue about making the shortcuts work across tabs please?
