### ISSUE TITLE
Catalina alerts user to "malicious software" and can't directly open

### ISSUE THREAD

**Issue by lucasderraugh** [git-up/GitUp#617] opened 2019-12-09 19:59 UTC
I think we'll need to send through Hardening and/or Notarization before release.
<img width="532" alt="Screen Shot 2019-12-09 at 11 55 46 AM" src="https://user-images.githubusercontent.com/714282/70467868-d7f96700-1a7a-11ea-9504-488acb83f4cc.png">

**Comment by hooch** [comment] 2019-12-12 22:57
How can I download 1.1?  I can't seem to find a link.

**Comment by lucasderraugh** [comment] 2019-12-12 23:34
@hooch There is no 1.1, the server only keeps the latest copy, which is 1.1.1 at present. You can always download the latest at gitup.co (link also in ReadMe). If you're stuck on this warning, you can right-click and hold down option key while hitting the "Open" menu item. You can also go into "Security & Privacy" in System Preferences and open it there after your first attempt.

**Comment by hooch** [comment] 2020-01-29 23:53
Thanks Lucas I dug 1.1 out of the trash.  What's involved with getting Gitup notarised properly?

**Comment by lucasderraugh** [comment] 2020-01-30 01:15
@hooch  I need to update the script @swisspol originally gave me to send the binary to apple and get a notary receipt and staple it to the binary. See this [support doc](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution/customizing_the_notarization_workflow). I find this [article](https://blog.zeplin.io/dev-journal-automate-notarizing-macos-apps-94b0b144ba9d) much more concise though.
One main thing that needs to happen though is the app needs to adopt the Hardened Runtime requirements. I don't think we'll have any issue with this, though I haven't tried. This task could be a separate PR.

**Comment by hooch** [comment] 2020-02-04 04:52
@lucasderraugh this appears to be resolved in 1.1.2?   Thank you!

**Comment by lucasderraugh** [comment] 2020-02-04 05:31
Nah, it’s still an issue on the first install. Updates via Sparkle are unaffected.

**Comment by saltcedar** [comment] 2020-03-18 10:38
I encountered the same problem now. Would prefer not to work-around Apple security, since I'm quite a novice at this stuff. Looking forward to a fix.

**Comment by lucasderraugh** [comment] 2020-03-22 18:20
Alright, finally figured out how to get our build to pass with hardening (make sure the xcconfig doesn't affect iOS). Hopefully with the next release I'll be able to send the app through notarization and we'll be on our way!

**Comment by lucasderraugh** [comment] 2020-03-25 00:18
Hmm, looks like there could be some Sparkle hurtles here as well. I'll keep working through this over time. I'd like to cut a new build for continuous this weekend so depending on the time I get we'll see how that will shape up.

**Comment by lucasderraugh** [comment] 2020-04-25 04:43
Alrighty folks, this should be resolved in the latest continuous release. This should land in stable in a few days assuming no major issues occur in the 1.1.3 build. If anyone can verify that either hasn't installed GitUp or wants to download it to a new user/computer, you can download the continuous build here: https://s3-us-west-2.amazonaws.com/gitup-builds/continuous/GitUp.zip

**Closed** 2020-04-25 04:43 UTC

**Comment by frankrausch** [comment] 2020-04-26 16:44
I can confirm that GitUp 1.1.3 (1036) from the continuous build link above opens correctly and without a notarization warning on a freshly installed macOS 10.15.4. 🎉
Thanks a lot! Great work.
