### ISSUE TITLE
Follow and import gitconfig IncludeIf

### ISSUE THREAD

**Issue by lukaswelte** [git-up/GitUp#380] opened 2017-11-15 10:42 UTC
GitUp makes a great job of reading the local gitconfig. 
But there is `IncludeIf` which allows to e.g. include a specific config for certain directories.

```
[includeIf "gitdir:~/Development/my_company/"]
  path = .gitconfig_my_company
```

This includeIf is read from the config but the contents of the config file are not imported and thereby not used.

**Comment by swisspol** [comment] 2017-11-23 14:57
For this to happen, libgit2 would need to support this feature. I don’t know if the latest version does.

**Comment by lukaswelte** [comment] 2018-06-11 09:36
Cause it was implemented in libgit2 as @deild mentioned, it could now be integrated into GitUp @swisspol? Or is there still something external missing?

**Comment by svdo** [comment] 2019-08-29 19:38
I would love to have this feature as well. 

Gitup is awesome, thanks!!!!

**Comment by svdo** [comment] 2019-08-29 19:40
Oh I think this issue is a duplicate of #315 by the way.

**Comment by lucasderraugh** [comment] 2019-08-29 19:46
Thanks! I’ll close this to make for one place to track this issue.

**Closed by lucasderraugh** 2019-08-29 19:46 UTC
Labels: enhancement
