### ISSUE TITLE
Stash: unable to stash files from working directory and invalid characters in OID.

### ISSUE THREAD

**Issue by lolgear** [git-up/GitUp#559] opened 2019-08-25 08:41 UTC
I don't want to split this issue into two, because it is one workflow.

Previously, I can stash files from Working Directory by navigating to stash view and press `S`.
Now, I can't do it.
Bad, right?

But if I press `Stash file` in Commit View, I can stash desired file.

However, it fails. Error: `unable to parse OID: contains invalid characters`.

```c
// libgit2
int git_oid_fromstrn(git_oid *out, const char *str, size_t length) {

	v = git__fromhex(str[p]);
        // v = -1
        // p = 3
        // str = "abc\nb3adaae083071a9ec4cfb5977104050320e33bc4 ba8dad9197dea38e8154f8cc64e9c0f25640427a Dmitry Lobanov <gaussblurinc@gmail.com> 1566721497 +0300\tOn master: logging_and_zip\n"
        if (v < 0) {            
          return oid_error_invalid("contains invalid characters");
        }
}
```

`abc` is my favorite name for stashes. Heh.

**Comment by lucasderraugh** [comment] 2019-08-26 01:10
Going to close this as a duplicate of #72 and reopen the original. It appears to be failing on the same error. The most helpful case would be if we can have a repo that reproduces this problem. If you're in this state and can share your repo, this would be very beneficial.

**Closed by lucasderraugh** 2019-08-26 01:10 UTC
