### ISSUE TITLE
1.3.3: Double-clicking a branch or commit in the main view crashes

### ISSUE THREAD

**Issue by jfirebaugh** [git-up/GitUp#877] opened 2022-12-07 20:15 UTC
Double-clicking a branch or commit in the main view crashes. The crash is 100% reproducible. It does not happen in 1.3.2.

Crash report: https://gist.github.com/jfirebaugh/3d7fc18ea3ca9d208829ab0c91f94d5c

**Comment by lucasderraugh** [comment] 2022-12-07 20:26
@jfirebaugh Always when the stable comes out that the issues come in 😅. My first guess is that it has something to do with the MRC to ARC migration changes we tried to make so we could move away from some manual reference counting code. The odd thing is that I'm unable to reproduce this on my own machine (M1 Max on Ventura).

Could you see if simply selecting a commit and hitting return (which should be the same as double-click) results in the same crash loop?

I can try giving you a build that reverts the ARC changes and see if that resolves your issue as well. I'll try to give that either tonight or tomorrow to you. In the meantime, you can use an old version of GitUp as we save all the releases on GitHub.

**Comment by lucasderraugh** [comment] 2022-12-08 00:24
@jfirebaugh Is it any commit or is there something special about the commit that fails? Either way I'll give you a build to try tomorrow most likely.

**Comment by jfirebaugh** [comment] 2022-12-08 00:55
It seems to be any commit in one particular repository (a big private monorepo with a long commit history). Other repositories I've tested are not affected.

**Comment by lucasderraugh** [comment] 2022-12-12 15:39
@jfirebaugh Btw I was able to reproduce this issue on a larger repo. I'm going to see if the ARC transition changes were the issue (most likely the case) and if reverting those changes resolves the issue I'll push out a new stable build reverting them.

**Comment by lucasderraugh** [comment] 2022-12-13 16:25
@jfirebaugh This should be fixed now in 1.3.4. I made some poor ARC transition decisions that ended up not being equivalent to what MRC had previously.

Let me know if for some reason you are still having this problem.

**Closed by lucasderraugh** 2022-12-13 16:25 UTC

**Comment by jfirebaugh** [comment] 2022-12-13 20:25
Confirmed, 1.3.4 works. Thanks!
