### ISSUE TITLE
Persist selected Show options among app relaunches.

### ISSUE THREAD

**Issue by paciej00** [git-up/GitUp#85] opened 2016-03-16 18:50 UTC
I'd like my selected 'Show' options to persist between app launches. For now I have to manually select options I'm interested in each time I quit and re-open the app.

![Show options](http://cl.ly/1I2w29282f1d/Screen%20Shot%202016-03-16%20at%2019.39.59.jpg)

**Comment by bishtawi** [comment] 2016-03-31 01:59
+1 on this. I like to see the Branch Labels instead of the Tag Labels. Its a little annoying to have to change it every time I reopen the app.

**Comment by JamesBucanek** [comment] 2016-04-15 00:57
OK, I'd be willing to take a stab at this one.

So here's my question, and please be gentle: How does one go about submitting a change to a project like this? I've only contributed to one open source project, and that was years ago, so I'm not sure what the recommended procedure is.

I tried to look this up, but apparently there are all kinds of ways to submit changes and I'm given to believe that each project has it's own preference (?), so any guidance would be welcome.

**Comment by swisspol** [comment] 2016-04-15 02:06
It's commendable that you're willing to contribute to an open-source project, but to be honest, starting with GitUp is going to be hard. The [contributing guidelines](https://github.com/git-up/GitUp/blob/master/CONTRIBUTING.md) are very strict. I accept very few PRs and the bar is very high: both because it's an app that's critical to the workflow of many developers, so one needs to be very careful about quality, but also because I just have very little time to dedicate to GitUp - I can't mentor or hand hold anyone unfortunately.

My recommendation is for you to fork GitUp and hack around a solution that works for you, without trying to make it an official PR, which is going to be much harder.

**Comment by JamesBucanek** [comment] 2016-04-17 01:38
I had a chance to look into this and here's what I found.

(1) First, quit a bit of effort had already been expended to make the view options persistent, at least for window restoration. The `-[GIMapViewController encodeRestorableStateWithCoder:]` and `-[GIMapViewController restoreStateWithCoder:]` methods were dutifully encoding and restoring the map view options.

Unfortunately, this was broken at two levels. First, there was no code that ever sent the `-invalidateRestorableState` message, so any changes to those options were never captured and the next time the window would be restored back to the defaults.

Secondly, there was a hack in the `Document` class that explicitly calls the map view controller's encoding methods, bypassing Cocoa's built-in window restoration memento pattern. This hack is described as being needs to support "Pre-Yosemite" systems, and I don't know enough about the warts of Cocoa window restoration to know why this hack is needed or if there's a better solution.

Regardless, if you want to fix this one issue you can add the following statement:
```
  [self.windowController.document invalidateRestorableState];
```
to the following methods:
```
  -[GIMapViewController toggleTagLabels:]
  -[GIMapViewController toggleBranchLabels:]
  -[GIMapViewController toggleVirtualTips:]
  -[GIMapViewController toggleTagTips:]
  -[GIMapViewController toggleRemoteBranchTips:]
  -[GIMapViewController toggleStaleBranchTips:]
```
This will trigger the document to re-encode its restoration state whenever the view options are modified.

That, at least, will fix the restoration bug. But this will only preserve the options when you quit the app with windows open, and then relaunch the app.

(2) I implemented a more general solution by replacing the view option instance variables in `GIMapViewController` (`_showsVirtualTips`, `_hidesTagTips`,` _hidesRemoteBranchTips`, `_hidesStaleBranchTips`,` _updatePending`) with properties and accessor methods that are backed by `NSUserDefaults`.

To associate the view settings with a repository, I added an abstract `@property(nonatomic,copy) NSMutableDictionary* persistentViewState;` property to `GCRepository`. This property maintains a mutable dictionary, suitable for storing arbitrary view state information. The property value is keyed to the path of the repository and stored in `NSUserDefaults`, so each repository has a independent view state dictionary.

I also added a couple of convenience methods to make it easier to maintain boolean view settings:
```
- (BOOL)boolViewStateForKey:(NSString*)key default:(BOOL)value;
- (BOOL)setBoolViewState:(BOOL)state forKey:(NSString*)key;
```

The property accessors in `GIMapViewController` are all implemented using these two methods.

I also deleted all of the window restoration code in `GIMapViewController`, since it is now obsolete.

Anyway, if you want these changes I'll be happy to do whatever I can to provide them to you. I've forked the GitUp project, and committed these changes to my local copy. Not sure what the next step should be.

**Comment by JamesBucanek** [comment] 2016-04-17 02:58
P.S. If you want a stricter separation between the view and data models, the `persistentViewState` property (and related methods) could be implemented as a category of `CGRepository`, since it doesn't use any data in the repository object, it just needs to be associated with the repository.

**Comment by swisspol** [comment] 2016-04-17 15:27
> Unfortunately, this was broken at two levels.

It's not broken: state restoration correctly restores the Map settings.

IIRC because `-invalidateRestorableState` is not reliable pre-Yosemite, the app has to explicitly call the state restoration methods.

If you want to write/read arbitrary user info associated with a repo, it's best to use the API on `GCRepository+Utilities.h" rather that `NSUserDefaults` where you'll have to handle key conflicts.

**Comment by JamesBucanek** [comment] 2016-04-18 00:00
> It's not broken: state restoration correctly restores the Map settings.

It's most definitely broken here, at least for the view settings in `GIMapViewController` and `GIGraphView`. Here's how I reproduce this:

1. In `GIMapViewController`, set breakpoints in `-encodeRestorableStateWithCoder:` and `-restoreStateWithCoder:`.
2. Launch the app and open a repo in a window.
3. `-encodeRestorableStateWithCoder:` is received once, shortly after the window is opened.
4. Change any map view settings from the pop-up, like turning off virtual branch tips.
5. Quit the app.
6. Note that a second `-encodeRestorableStateWithCoder:` was never received...
7. Launch the app again.
8. `GIMapViewController` receives a `-restoreStateWithCoder:`, but the values that get decoded are the old (original) values when the window was first opened because `-encodeRestoreableStateWithCoder:` was never received again, so the encoded values were never updated to reflect the changes made to the view options.

This is 100% reproducible on my system (OS X 10.11.4).

> If you want to write/read arbitrary user info associated with a repo, it's best to use the API on `GCRepository+Utilities.h` rather that `NSUserDefaults` where you'll have to handle key conflicts.

I looked at `-[GCRepository(Utilities) setUserInfo:forKey:]` and `-[CGRepository(Utilities) userInfoForKey:]`, but they appear to store property values in the repository.

I was striving to save persistent view state information on a per-user/per-repro basis, rather than just a per-repo basis, because multiple users could conceivably be viewing the same repository (say, on a network volume) and another user's view settings shouldn't change my view settings.

But maybe that's a edge case that hardly ever happens. It would be trivial to refactor my code to use `GCRepository(Utilities)` instead of `NSUserDefaults`.

**Comment by swisspol** [comment] 2016-04-18 03:03
> Here's how I reproduce this:

Works for me on 10.11.4: map view custom settings like "Orphan branch tips" are preserved when quitting / relaunching the app. You must have "Close windows when quitting apps" disabled in System Preferences / General.

> I was striving to save persistent view state information on a per-user/per-repo basis, rather than just a per-repo basis, because multiple users could conceivably be viewing the same repository (say, on a network volume) and another user's view settings shouldn't change my view settings.

Open the same repo multiple times in GitUp through a shared volume or equivalent is not going to work right anyway, and GitUp already stores per-repo info in the repo as well.

**Comment by JamesBucanek** [comment] 2016-04-18 06:22
> You must have "Close windows when quitting apps" disabled in System Preferences / General.

I don't, but I can't rule out that there's just something weird with my system.

I've refactored my code to use `-[GCRepository(Utilities) userInfoForKey:]` and `-[GCRepository(Utility) setUserInfo:forKey:]` to store the view options.

Would you rather see the utility methods for maintaining these settings added to `GCRepository(Utilities)` or isolated in a new category (`GCRepository(ViewState)`)?

**Comment by swisspol** [comment] 2016-04-18 13:51
> 
I don't, but I can't rule out that there's just something weird with my system.

If you have close Windows when quitting apps enabled in the System Preferences, then this disables window restoration, there's nothing abnormal with your OS. So does this work for you or not?

**Comment by swisspol** [comment] 2016-04-18 15:19
> Would you rather see the utility methods for maintaining these settings added to GCRepository(Utilities) or isolated in a new category (GCRepository(ViewState))?

This can't go in `GCRepository(Utilities)` since this is non-UI code that lives there. It just needs to live in `GIMapViewController.m`. Read the saved UI settings in `initWithRepository:` and save them whenever they change in one of the `setShowsVirtualTips:` methods and friends. There's no need for utility methods, it's just a handful of call sites.

**Comment by JamesBucanek** [comment] 2016-04-18 20:13
OK, I've got it all distilled down to a pretty simple set of changes. I even managed to squash all of my commits into a single commit—so it's been a good learning experience.

**Comment by JamesBucanek** [comment] 2016-04-18 20:40
> If you have close Windows when quitting apps enabled in the System Preferences, then this disables window restoration, there's nothing abnormal with your OS. So does this work for you or not?

I normally leave the _Close windows when quitting_ option on, but I made sure to turn it off for these tests.

Funny story: Works if you just run the app. Doesn't work if you try to debug it in Xcode. (:sadface:, because that's not that funny.)

I tested it several more times. I tested by double-clicking the GitUp.app in the Debug build folder, running the app from Xcode with no breakpoints set, and again with breakpoints in `-encodeRestorableStateWithCoder:` and `-restoreStateWithCoder:`. The window states get restored in the first two scenarios, but does not get save/restored if you hit these breakpoints.

**Comment by swisspol** [comment] 2016-04-18 23:15
> I even managed to squash all of my commits into a single commit

I think this should actually be 2 commits:
- one to add the new feature and use repo user info to store map settings
- one to remove all the code for window state restoration

You can send a PR and will have a look soon.

In the meantime, I'm closing this issue, since the app is currently behaving as expected.

**Closed by swisspol** 2016-04-18 23:15 UTC
Labels: enhancement
