### ISSUE TITLE
GitUp gets stuck in a diverging branches window forever

### ISSUE THREAD

**Issue by berkus** [git-up/GitUp#1019] opened 2024-08-07 11:44 UTC
<img width="792" alt="image" src="https://github.com/user-attachments/assets/84b199f4-2723-4fba-9a71-5dc1b16430d5">

None of the buttons close the dialog, and could not quit GitUp while it's active. This current screenshot is after I've already resolved the situation in the terminal, it's still stuck in the GUI.

Repro steps:
- make a branch
- force push it from a different instance
- try to pull that branch from GitUp on the first instance, goes into this dialog and cannot be closed

**Comment by berkus** [comment] 2024-08-07 11:45
If you try to quit you'll get this:

<img width="802" alt="image" src="https://github.com/user-attachments/assets/f3c3caf2-eec4-40d6-aa94-4c2a8324d3e1">

**Comment by lucasderraugh** [comment] 2024-08-07 16:08
Thanks for the feedback. This is an issue that I'll flag as we've had previous reports.
Duplicate of #793

**Closed by lucasderraugh** 2024-08-07 16:08 UTC
