### ISSUE TITLE
Branch names are rendered out of the viewport 

### ISSUE THREAD

**Issue by pouyakary** [git-up/GitUp#958] opened 2023-12-27 15:43 UTC
Version 1.3.5 (1048)

Hi everyone! thanks for the amazing amazing app and happy holidays!

In the case of long branch names, the branches are rendered out of the viewport and I can't read them:

![](https://github.com/git-up/GitUp/assets/2157285/d43a1cdb-fc33-401b-bf67-78ae34f014f1)

**Comment by lucasderraugh** [comment] 2024-01-21 01:36
Duplicate of #94

**Closed** 2024-01-21 01:37 UTC
