### ISSUE TITLE
SSH authentication

### ISSUE THREAD

**Issue by charpov** [git-up/GitUp#576] opened 2019-09-06 17:09 UTC
I have a remote that uses SSH (with a `git@...` URL).  I have 2 identities in `~/.ssh/`.  The server is only set up with one of the public keys.

Remote accesses work fine from the command-line git client.  GitUp, however, prompts me for a user and password (note that the remote is not HTTPS).  Running `ssh-add` in a terminal window solves the problem (until reboot).

According to the documentation GitUp tries all the keys from `~/.ssh/`.  Why doesn't it work?  Am I missing a step?

**Comment by lolgear** [comment] 2019-09-07 16:01
Add to `~/.bash_profile`

```
ssh-add -AK # add all keys from keychain to current session
```

**Comment by douglashill** [comment] 2019-09-07 16:30
That was my conclusion too. Basically you have to open some sort of terminal before GitUp will be able to read the SSH key.

SSH keys could be added a login a few version of the OS ago and it seems Apple changed it so this is no longer possible.

**Comment by lucasderraugh** [comment] 2019-09-11 19:41
I think this is a duplicate of the SSH discussion in this thread: #35

**Closed by lucasderraugh** 2019-09-11 19:41 UTC
